name: QA-0 Auto-Verify

# Triggers when a PR's check suite completes successfully
on:
  check_suite:
    types: [completed]

jobs:
  auto-verify:
    # Only run if all checks passed
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.payload.check_suite.head_branch}`,
              state: 'open'
            });
            
            if (prs.length === 0) {
              console.log('No open PR found for this branch');
              return null;
            }
            
            const pr = prs[0];
            console.log(`Found PR #${pr.number}: ${pr.title}`);
            
            // Extract issue number from PR body (looks for "Closes #123" or "Fixes #123")
            const issueMatch = pr.body?.match(/(?:closes|fixes|resolves)\s+#(\d+)/i);
            if (!issueMatch) {
              console.log('No linked issue found in PR body');
              return null;
            }
            
            const issueNumber = parseInt(issueMatch[1]);
            console.log(`Linked to issue #${issueNumber}`);
            
            return { pr: pr.number, issue: issueNumber };
      
      - name: Check for qa-grade:0 label
        id: check-grade
        if: steps.pr.outputs.result != 'null'
        uses: actions/github-script@v7
        with:
          script: |
            const prData = ${{ steps.pr.outputs.result }};
            if (!prData) return false;
            
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prData.issue
            });
            
            const hasQaGrade0 = issue.labels.some(l => l.name === 'qa-grade:0');
            const hasStatusQa = issue.labels.some(l => l.name === 'status:qa');
            
            console.log(`Issue #${prData.issue} labels: ${issue.labels.map(l => l.name).join(', ')}`);
            console.log(`Has qa-grade:0: ${hasQaGrade0}`);
            console.log(`Has status:qa: ${hasStatusQa}`);
            
            // Only auto-verify if:
            // 1. Issue has qa-grade:0 label
            // 2. Issue is currently in status:qa (meaning handoff happened)
            return hasQaGrade0 && hasStatusQa;
      
      - name: Auto-verify via Crane Relay
        if: steps.check-grade.outputs.result == 'true'
        env:
          RELAY_TOKEN: ${{ secrets.CRANE_RELAY_TOKEN }}
        run: |
          PR_DATA='${{ steps.pr.outputs.result }}'
          ISSUE_NUMBER=$(echo "$PR_DATA" | jq -r '.issue')
          PR_NUMBER=$(echo "$PR_DATA" | jq -r '.pr')
          REPO="${{ github.repository }}"
          COMMIT_SHA="${{ github.event.check_suite.head_sha }}"
          
          echo "Auto-verifying issue #$ISSUE_NUMBER (PR #$PR_NUMBER)"
          echo "CI passed for commit $COMMIT_SHA"
          
          # Submit QA result via V2 events endpoint
          curl -s -X POST "https://crane-relay.automation-ab6.workers.dev/v2/events" \
            -H "X-Relay-Key: $RELAY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "event_id": "qa0-auto-'"$ISSUE_NUMBER"'-'"$(date +%s)"'",
              "repo": "'"$REPO"'",
              "issue_number": '"$ISSUE_NUMBER"',
              "role": "QA",
              "agent": "github-actions-qa0",
              "event_type": "qa.result_submitted",
              "environment": "preview",
              "overall_verdict": "PASS",
              "summary": "QA-0: CI passed, auto-verified",
              "build": {
                "pr": '"$PR_NUMBER"',
                "commit_sha": "'"$COMMIT_SHA"'"
              },
              "scope_results": [
                { "id": "CI", "status": "PASS", "notes": "All checks passed" }
              ]
            }'
          
          echo ""
          echo "✅ Issue #$ISSUE_NUMBER auto-verified (qa-grade:0 + CI pass)"
